version: 2

sources:
  - name: coffee_shop
    project: analytics-engineers-club
    description: source coffee shop data for analytics engineers club

    tables:
      - name: orders
        description: order data for coffee shop
        # freshness:
        #   error_after:
        #     count: 12
        #     period: hour
        # loaded_at_field: created_at          
        columns:
          - name: id
            description: primary key for orders
            tests:
              - unique
              - not_null
          - name: customer_id
            description: foreign key to id in customer table        
      - name: customers
        description: customer data for coffee shop
        columns:
          - name: id
            description: primary key for customers
            tests:
              - unique
              - not_null